##Set server names
Servers:
    lobby: "&9Lobby"
    survival: "&6Survival Server"
    mining: "&9Mining Server"
    staff: "&4Staff Server"
    ???: "&7Unknown Server"
Messages:
    ##Syntax: %player%,%to%,%from%
    SwapServerMessage: "&6&l%player%&r  &7[%from%&7] -> [%to%&7]"
    JoinNetworkMessage: "&6%player% &6has connected to the network!"
    LeaveNetworkMessage: "&6%player% &6has disconnected from the network!"
    ##Not yet implemented.
    ##FirstTimeConnectedMessage: "&6%player% has connectet to the network for the first time!"
Settings:
    ##Should players with the bungeejoinmessages.silent permission be silenced by default? It will be set to this for all players after a reboot.
    SilentJoinDefaultState: true
    ##Should the following messages be enabled?
    SwapServerMessageEnabled: true
    JoinNetworkMessageEnabled: true
    LeaveNetworkMessageEnabled: true
    ##Should other players with the bungeejoinmessages.silent permission be notified of players moving silently?
    NotifyAdminsOnSilentMove: true