##Set server names
Servers:
    lobby: "&9Lobby"
    survival: "&6Survival Server"
    mining: "&9Mining Server"
    staff: "&4Staff Server"
    ???: "&7Unknown Server"
Messages:
    ##Syntax: %player%,%to%,%from%
    SwapServerMessage: "&6&l%player%&r  &7[%from%&7] -> [%to%&7]"
    SwapServerArgumentsComment: 
        - 'Note: Changing these will have no effect. You can delete the entire SwapServerArgumentsComment if you want.'
        - '%player% (The playes name)'
        - '%to% the server they are heading to'
        - '%from% the server they are coming from'
        - '%playercount_from% The amount of players where they are coming from.' 
        - '%playercount_to% The amount of players where they are heading to.' 
        - '%playercount_network% The amount of players on the network.'
    JoinNetworkMessage: "&6%player% &6has connected to the network!"
    JoinNetworkArgumentsComment:
        - 'Note: Changing these will have no effect. You can delete the entire JoinNetworkArgumentsComment if you want.'
        - '%player%: (The playes name)'
        - '%playercount_server%: The playercount of the server they are on.'
        - '%playercount_network%: The playercount of the network.'
    LeaveNetworkMessage: "&6%player% &6has disconnected from the network!"
    LeaveNetworkArgumentsComment:
        - 'Note: Changing these will have no effect. You can delete the entire LeaveNetworkArgumentsComment if you want.'
        - '%player%: (The playes name)'
        - '%playercount_server%: The playercount of the server they are on.'
        - '%playercount_network%: The playercount of the network.'
    ##Not yet implemented.
    ##FirstTimeConnectedMessage: "&6%player% has connectet to the network for the first time!"
##New in v.1.3
Settings:
    ##Should players with the bungeejoinmessages.silent permission be silenced by default? It will be set to this for all players after a reboot. They can toggle it for themselves with the /fakemessage toggle command
    SilentJoinDefaultState: true
    ##Should the following messages be enabled?
    SwapServerMessageEnabled: true
    JoinNetworkMessageEnabled: true
    LeaveNetworkMessageEnabled: true
    ##Should other players with the bungeejoinmessages.silent permission be notified of players moving silently?
    NotifyAdminsOnSilentMove: true