name: ${name}
version: ${version}
description: ${description}
author: ${author}
website: ${url}

main: ${mainClass}

commands:
    fakemessage:
        description: Send a fake join or leave message from bungee
        permission: bungeejoinmessage.fakemessage
        usage: /<command>
        aliases: [fm]
permissions:
    bungejoinmessages.fakemessage:
        description: "Allows the use of the fakemessage command"
        default: op
    bungeejoinmessages.silent:
        description: "lets you join the server without notifications."
        default: false